Vagrant.configure("2") do |config|

  # app server 1
  config.vm.define "app1" do |node|
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.hostname = "app1"
    node.vm.network "private_network", ip: "192.168.33.10"
  end

  # app server 2
  config.vm.define "app2" do |node|
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.hostname = "app2"
    node.vm.network "private_network", ip: "192.168.33.11"
  end

  # load balancer
  config.vm.define "web" do |node|
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.hostname = "web"
    node.vm.network "forwarded_port", guest: 80, host: 8080
  end

end
